---
title: "RWorksheet_Porras#4A"
output: pdf_document
date: "2023-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
#number 1
  HouseHold <- data.frame(
  ShoeSize =c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),
  Height =c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0),
  Gender = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
  )
  HouseHold
  
  
```


```{r}

#number2
months_vector <- c("March","April","January","November","January","September","October","September","November","August",
"January","November","November","February","May","August",
"July","December","August","August","September","November","February","April")

factor_months_vector <- factor(months_vector)
factor_months_vector
```

```{r}
#number 3
summary(months_vector)
summary(factor_months_vector)
```

```{r}
#number4

direction <- c("East","West","North")

factor_data <- c(1,4,3)

new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```

```{r}
#number 5 on working process+++
read.table(inport_march)
```

```{r}
# number 6
randomNum <- readline(prompt = "Enter number from 1 to 50: ")
randomNum <- as.numeric(randomNum)
paste("The number you have chosen is", randomNum)
if (randomNum > 50) {
  paste("The number selected is beyond the range of 1 to 50")
} else if (randomNum == 20) {
  paste("TRUE")
} else {
  paste(randomNum)
}
```

```{r}
# number 7
minimumBills <- function(price) {
  
  minBills <- price %/% 50
  paste("The minimum no. of bills:", minBills)
}
minimumBills(90)
```

```{r}
#number 8 A
Students_Math <-data.frame(
Names = c("Annie", "Thea", "Steve", "Hanna"),
Grade_1 =c(85,65,75,95),
Grade_2 =c(65,75,55,75),
Grade_3 =c(85,90,80,100),
Grade_4 =c(100,90,85,90)
)

#number 8B
Students_Math $Average <-(Students_Math$Grade_1 + Students_Math$Grade_2 + Students_Math$Grade_3 + Students_Math$Grade_4) / 4

print(Students_Math)
```




