---
title: "RWorkSheet_Porras#4b"
author: "Porras, Christian"
date: "2023-11-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


#1
vector_a<- c(1,2,3,4,5)
matrix_A <- matrix(0,nrow = 5, ncol =5)

for (c in 1:5)
for (p in 1:5)

{
matrix_A[c,p] <-abs (vector_a[c] - vector_a[p])
}

matrix_A
```

```{r}
#2

for (c in 1:5){
cat(paste0("\"", rep("*",c),"\""),"\n")
}
```

```{r}
userInput <- as.integer(readline("Enter starting number for Fibonacci sequence: "))

if(is.na(userInput || userInput < 0)) {
  cat("Please Enter Something")
} else {
 
x <- userInput
y <- 0


cat("Fibonacci sequence starting from", userinpuT, ":\n")

repeat {
 
  next_num <- x + y
 
  if (next_num > 500){
    break
  }
  cat(next_num, " ")
  x <- y
  y <- next_num
 
}
}

```

```{r}
#4 
  HouseHold <- data.frame(
  ShoeSize =c(6.5,9.0,8.5,8.5,10.5,7.0,9.5,9.0,13.0,7.5,10.5,8.5,12.0,10.5,13.0,11.5,8.5,5.0,10.0,6.5,7.5,8.5,10.5,8.5,10.5,11.0,9.0,13.0),
  Height =c(66.0,68.0,64.5,65.0,70.0,64.0,70.0,71.0,72.0,64.0,74.5,67.0,71.0,71.0,77.0,72.0,59.0,62.0,72.0,66.0,64.0,67.0,73.0,69.0,72.0,70.0,69.0,70.0),
  Gender = c("F","F","F","F","M","F","F","F","M","F","M","F","M","M","M","M","F","F","M","F","F","M","M","F","M","M","M","M")
  )
  
write.csv(HouseHold, file = "HouseHold.csv", row.names = FALSE)


#4.a
print(HouseHold[1:6,])
```

```{r}

prevData <- read.csv("HouseHold.csv")
head(prevData)

males <- prevData[prevData$Gender == "M",]
males

females <- prevData[prevData$Gender == "F",]
females

numofMale <- nrow(males)
numofMale

numofFem <- nrow(females)
numofFem
```

```{r}
# C. Create a graph for the number of males and females for Household Data. Use plot(),chart type = barplot. Make sure to place title, legends, and colors. Write the R scripts and its result.
totalMaleFemale <- table(prevData$Gender)
barplot(totalMaleFemale,
        main = "Number of Males and Females",
        xlab = "Gender",
        ylab = "Count",
        col = c("red", "blue"),
        legend.text = rownames(totalMaleFemale),
        beside = TRUE)
```

```{r}
#5. The monthly income of Dela Cruz family was spent on the following:
# A. Create a piechart that will include labels in percentage.Add some colors and title of the chart. Write the R scripts and show its output.


spending_data <- data.frame(
  Category = c("Food", "Electricity", "Savings", "Miscellaneous"),
  Value = c(60, 10, 5, 25)
)

spending_data$Percentage <- spending_data$Value / sum(spending_data$Value) * 100

colors <- c("blue", "lightgreen", "red", "orange")

pie(spending_data$Value,
    labels = paste(spending_data$Category, "(",spending_data$Percentage,"%)"),
    col = colors,
    main = "Monthly Income Spending of Dela Cruz Family")

legend("topright", spending_data$Category, fill = colors)

```
6. Use the iris dataset

```{r}
data(iris)
```


```{r}
#A. Check for the structure of the dataset using the str() function. Describe what you have seen in the output.

str(iris)

## -The dataset provides information on 150 different iris flowers, including their sepal and petal lengths and widths, and their iris species, including setosa, versicolor, and virginica, and records the type of flower each belongs to.

```


```{r}
# B. Create an R object that will contain the mean of the sepal.length, sepal.width,petal.length,and petal.width. What is the R script and its result?
  
meanOfFlowerS <- colMeans(iris[,1:4])
meanOfFlowerS
```



```{r}
# C. Create a pie chart for the Species distribution. Add title, legends, and colors. Write the R script and its result.

specieS <- table(iris$Species)
nameOfspecieS <- c("Setosa", "Versicolor", "Virginica")

pie(specieS,
    labels = nameOfspecieS,
    col = c("red", "white", "cyan"),
    main = "Species Distribution In Iris Dataset")

legend("topleft", legend = levels(iris$Species), fill = c("red", "white", "cyan"),)
```



```{r}
#D. Subset the species into setosa, versicolor, and virginica. Write the R scripts and show the last six (6) rows of each species.

iris
SubseTSetosa <- iris[iris$Species == "Setosa",]
SubseTSetosa

SubseTVersicolor <- iris[iris$Species == "Versicolor",]
SubseTVersicolor

SubseTVirginica <- iris[iris$Species == "Virginica",]
SubseTVirginica

tail(SubseTSetosa)
tail(SubseTVersicolor)
tail(SubseTVirginica)
```



```{r}

#E. Create a scatterplot of the sepal.length and sepal.width using the different species(setosa,versicolor,virginica). Add a title = “Iris Dataset”, subtitle = “Sepal width and length, labels for the x and y axis, the pch symbol and colors should be based on the species.
plot(iris$Sepal.Length, iris$Sepal.Width,
     xlab = "Sepal Length", ylab = "Sepal Width",
     main = "Iris Dataset", sub = "Sepal Width and Length",
     pch = as.numeric(iris$Species), col = as.numeric(iris$Species))

legend("topright", legend = levels(iris$Species),
       pch = 1:3, col = 1:3,
       title = "SPECIES")
#F. Interpret the result.
#The Scatterplot enables us to observe the variations in sepal length and width among various species of iris flowers.

#The Setosa flowers, characterized by their short sepal length and wide width, are typically found in the upper left part of the plot.
#The Versicolor flowers have an average sepal length and width, located in the middle part.
#The Virginica flowers are typically long in sepal length and narrower in width, forming a group in the right part.
#Based on the plot, the differences between the three Iris species can be easily observed based on the differences in sepal length and width.

```


```{r}


#7. Import the alexa-file.xlsx. Check on the variations. Notice that there are extra whitespaces among black variants (Black Dot, Black Plus, Black Show, Black Spot). Also on the white variants (White Dot, White Plus, White Show, White Spot).

library(readxl)

Alexa_File <- read_excel("Alexa_File.xlsx")
Alexa_File
```



```{r}
#A. Rename the white and black variants by using gsub() function.


Alexa_File$variation <- gsub("White  Dot", "WhiteDot", Alexa_File$variation)
Alexa_File$variation <- gsub("White  Plus", "WhitePlus", Alexa_File$variation)
Alexa_File$variation <- gsub("White  Show", "WhiteShow", Alexa_File$variation)
Alexa_File$variation <- gsub("White  Spot", "WhiteSpot", Alexa_File$variation)

Alexa_File$variation <- gsub("Black  Dot", "BlackDot", Alexa_File$variation)
Alexa_File$variation <- gsub("Black  Plus", "BlackPlus", Alexa_File$variation)
Alexa_File$variation <- gsub("Black  Show", "BlackShow", Alexa_File$variation)
Alexa_File$variation <- gsub("Black  Spot", "BlackSpot", Alexa_File$variation)

Alexa_File

```



```{r}
#B. Get the total number of each variations and save it into another object. Save the object as variations.RData. Write the R scripts. What is its result? 

install.packages("dplyr")
library("dplyr")

variations_Total <- Alexa_File %>%
  count(Alexa_File$variation)

variations_Total
save(variations_Total, file = "VariaTionS.RData")
```



```{r}
# C. From the variations.RData, create a barplot(). Complete the details of the chart which include the title, color, labels of each bar.

load ("VariaTionS.RData")
variations_Total
varNames <- variations_Total$'Alexa_File$variation'

totalPlot <- barplot(variations_Total$n,
                     names.arg = varNames,
                     main = "Total Number Of Each Variations",
                     xlab = "Name Of Variations",
                     ylab = "Total Of Each Variations",
                     col = 1:16,
                     space = 0.1,
                     cex.names = 0.5,
                     las = 2 )
```

```{r}
#D. Create a barplot() for the black and white variations. Plot it in 1 frame, side by side. Complete the details of the chart.


blackVars <- variations_Total[variations_Total$`Alexa_File$variation` %in% c("Black", "BlackPlus" , "BlackShow" ,"BlackSpot" , "BlackDot"), ]

whiteVars <- variations_Total[variations_Total$`Alexa_File$variation` %in% c("White", "WhiteDot", "WhitePlus", "WhiteShow", "WhiteSpot"), ]

par(mfrow = c(1,2))
blackVars

blackPlot <- barplot(height = blackVars$n,
        names.arg = blackVars$`Alexa_File$variation`,
        col = c("lightblue"),
        main = "Black Variations",
        xlab = "Variation",
        ylab = "Count",
        border = "red",
        space = 0.5,
        cex.names = 0.4)


whitePlot <- barplot(height = whiteVars$n,
        names.arg = whiteVars$`Alexa_File$variation`,
        col = c("blue"),
        main = "White Variations",
        xlab = "Variation",
        ylab = "Count",
        border = "red",
        space = 0.5,
        cex.names = 0.4)


```

